# Generated by Django 3.1.1 on 2021-04-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swpsdata', '0006_mc_devicedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(blank=True, max_length=50)),
                ('CourseDescription', models.TextField(blank=True, max_length=10000)),
                ('Question', models.TextField(blank=True, max_length=10000)),
                ('Answer', models.TextField(blank=True, max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='cl_DeviceData',
        ),
        migrations.DeleteModel(
            name='mc_DeviceData',
        ),
        migrations.DeleteModel(
            name='ss_DeviceData',
        ),
        migrations.DeleteModel(
            name='tp_DeviceData',
        ),
    ]
